services:
    app:
        extends:
            file: templates.yml
            service: base-app
        image: 'sail-8.4/app'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        depends_on:
            - pgsql
            - redis
            - soketi
    queue-default:
        extends:
            file: templates.yml
            service: base-app
        build:
            context: './docker/8.4'
            dockerfile: Dockerfile
        image: 'sail-8.4/custom-app'
        environment:
            CONTAINER_ROLE: queue
            WORK_ON_QUEUES: default
            APP_ENV: ${APP_ENV:-local}
        depends_on:
            - pgsql
            - redis
            - soketi
    queue-game-loop:
        extends:
            file: templates.yml
            service: base-app
        build:
            context: './docker/8.4'
            dockerfile: Dockerfile
        image: 'sail-8.4/custom-app'
        environment:
            CONTAINER_ROLE: queue
            WORK_ON_QUEUES: game-loop
            APP_ENV: ${APP_ENV:-local}
        depends_on:
            - pgsql
            - redis
            - soketi
    pgsql:
        image: 'postgres:17'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        command: /bin/sh -c "redis-server --requirepass $REDIS_PASSWORD"
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        environment:
            SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID}'
            SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY}'
            SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET}'
        ports:
            - '${PUSHER_PORT:-6001}:6001'
            - '${PUSHER_METRICS_PORT:-9601}:9601'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
